spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handi
    username: handi
    password: ssafyhandia306
    driver-class-name: org.postgresql.Driver

  
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  
  # Redis configuration (commented out for initial setup)
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     timeout: 2000ms

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs 